### ISSUE TITLE
XDG_DATA_DIRS must be split

### ISSUE THREAD

**Issue by andir** [liamg/fontinfo#1]
In https://github.com/liamg/fontinfo/blob/master/match.go#L28 you are treating `XDG_DATA_DIRS` as if it would only ever list one directory. In reality it is a `:` separated list of paths (which each has to be suffixed with `/fonts`).

>$XDG_DATA_DIRS defines the preference-ordered set of base directories to search for data files in addition to the $XDG_DATA_HOME base directory. The directories in $XDG_DATA_DIRS should be seperated with a colon ':'.
>
> If $XDG_DATA_DIRS is either not set or empty, a value equal to /usr/local/share/:/usr/share/ should be used. 

Source: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by liamg** [comment]
Good spot, thanks! I'll fix this tonight :+1:

**Comment by liamg** [comment]
Fixed in `v0.1.1` :+1:
